---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Here are some plots

I am making interactive plots in plotly. I'll make plots using the Instacart dataset.

```{r, set up, message=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Do some initial data cleaning 

```{r, message=FALSE}
data(instacart)
instacart_ploty = 
  instacart |> 
  select(order_dow, order_hour_of_day, days_since_prior_order, aisle, department)|>
    drop_na() |> 
    sample_n(13000)
```

Order of different Department Distribution by Day of the Week
```{r, message=FALSE, warning=FALSE}
instacart_ploty |> 
  filter(department != "missing") |>
  mutate(order_dow = factor(order_dow, 
                            levels = 0:6, 
                            labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))) |> 
  group_by(order_dow,department) |> 
  summarise(order_amount = n()) |> 
  plot_ly( x = ~order_dow, y = ~order_amount, color = ~department, type = "bar", colors = "viridis")|> 
layout(
    title = "Order Distribution by Day of the Week and Department",
    xaxis = list(title = "Day of the Week"),
    yaxis = list(title = "Order Amount"),
    barmode = "stack"
  )
```

Average Weekly Orders of each department by Hour of the Day
```{r, warning=FALSE, message=FALSE}
instacart_ploty |> 
  filter(department != "missing") |>
  group_by(department, order_hour_of_day) |> 
  summarise(order_amount = n()/7)|> 
plot_ly(x = ~order_hour_of_day, y = ~order_amount, color = ~department, type = "scatter", mode = "lines+markers", colors = "viridis")|> 
  layout(title = "Average Weekly Orders of each department by Hour of the Day",
         xaxis = list(title = "Hour of the Day"),
         yaxis = list(title = "Average Weekly Orders per Hour"))
```

How does the days_since_prior_order vary across different aisle

```{r, warning=FALSE}
instacart_ploty |> 
    filter(aisle != "missing") |>
    mutate(aisle = fct_reorder(aisle, days_since_prior_order)) |> 
  plot_ly(x = ~aisle,  y = ~days_since_prior_order, type = "box", color = ~aisle , colors = "viridis" ) |>
  layout(title = "Distribution of Days Since Prior Order Across Aisles",
    xaxis = list(title = "Aisle"),
    yaxis = list(title = "Days Since Prior Order")
  )
```
